#!/usr/bin/env bash
# set a user in the config by replace '#user' and it's value

# replaces port 80 with 8080 in the sites-available config
# gives owner permissions to read and write to the config file
# apache may interfere with nginx so kills the process if it is running
# starts the nginx service with the new nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
